Added proper versions of CLP(R) compilable from source

diff --git a/dist/tracer b/dist/tracer
--- a/dist/tracer
+++ b/dist/tracer
@@ -8,6 +8,10 @@
 #============================================================================#
 
 # Paths
+if [ x$TRACER_PATH == x ]; then
+    echo "The environment variable TRACER_PATH is not set: Aborting."
+    exit 1
+fi
 CLPRPATH=$TRACER_PATH/lib
 MAIN_CLPR=src/tracer.0.1
 
